USE MuOnline
UPDATE Guild SET G_Score = 0 WHERE G_Score IS NULL OR G_Score < 0
ALTER TABLE Guild ALTER COLUMN G_Score int NOT NULL
ALTER TABLE Guild ADD CONSTRAINT DF_G_Score DEFAULT 0 for G_Score
GO
UPDATE Guild SET G_Count = 0 WHERE G_Count IS NULL OR G_Count < 0
ALTER TABLE Guild ALTER COLUMN G_Count int NOT NULL
ALTER TABLE Guild ADD CONSTRAINT DF_G_Count DEFAULT 0 for G_Count